# .github/workflows/ci-cd.yml
name: CI / Release

on:
  push:
    branches: [ master ]
    tags: ['v*.*.*']     # also trigger when you push a semver tag

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rid: [linux-x64, linux-arm64, macos-x64, macos-arm64, win-x64]    # add macos‑x64, win‑x64, etc. if you want
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore & Build
        run: dotnet restore
      - run: dotnet build --configuration Release --no-restore

      - name: Publish for ${{ matrix.rid }}
        run: |
          dotnet publish \
            --configuration Release \
            --runtime ${{ matrix.rid }} \
            --self-contained false \
            --output ./publish/${{ matrix.rid }}

      # If this is a release (i.e. we pushed a tag), upload each RID binary as a release asset
      - name: Upload release assets
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            publish/${{ matrix.rid }}/RewindSubtitleDisplayerForPlex*
            
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push multi‑arch image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/plex-show-subtitles-on-rewind:${{ github.ref_name == '' && 'latest' || github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/plex-show-subtitles-on-rewind:latest
