name: Release Drafter
on:
  push:
    branches: [ master ]
  pull_request:
    types: [ closed ]
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
